apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: carbonetes-scan
spec:
  homepage: https://github.com/carbonetes/kubectl-carbonetes-scan
  shortDescription: Integrates container analysis directly into your cluster.
  version: v1.0.0
  description: |
    Provides complete container analysis and
    policy evaluation as a fully managed service.
    Carbonetes analyzes your container images for native
    code vulnerabilities, software composition analysis (SCA),
    license types, malware, secrets, and bill of materials.
  caveats: |
    Docker needs to be installed on your machine to use this plugin.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/carbonetes/kubectl-carbonetes-scan/archive/refs/tags/v1.0.1.tar.gz
    sha256: 6c9db80385ac7d2452c1ee0aaf1977f9858eef32862c349a7f6a7d730717dfb3
    bin: kubectl-carbonetes-scan
    files:
    - from: kubectl-carbonetes-scan-*/kubectl-carbonetes-scan
      to: .
    - from: kubectl-carbonetes-scan-*/LICENSE
      to: .